// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5kpRxNCDEpygGQBBSRKgmWgO2t30bBE0',
    appId: '1:690790414473:web:850d5453244c5ca051ae58',
    messagingSenderId: '690790414473',
    projectId: 'appviajesegurobas',
    authDomain: 'appviajesegurobas.firebaseapp.com',
    storageBucket: 'appviajesegurobas.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoT0bXOYjU8HfemMU3-TEJR7b4Xjhle5I',
    appId: '1:690790414473:android:f369bfd4120afcd051ae58',
    messagingSenderId: '690790414473',
    projectId: 'appviajesegurobas',
    storageBucket: 'appviajesegurobas.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5kpRxNCDEpygGQBBSRKgmWgO2t30bBE0',
    appId: '1:690790414473:web:f0f60f67de0a5df651ae58',
    messagingSenderId: '690790414473',
    projectId: 'appviajesegurobas',
    authDomain: 'appviajesegurobas.firebaseapp.com',
    storageBucket: 'appviajesegurobas.appspot.com',
  );
}
